---

- name: PAGESPEED_EXPORTER | Copy Daemon script
  template:
    src: pagespeed_exporter.service.j2
    dest: /etc/systemd/system/pagespeed_exporter.service
    mode: 0644
    owner: root
    group: root
  notify: restart pagespeed_exporter

- name: PAGESPEED_EXPORTER | Configuring service
  systemd:
    name: pagespeed_exporter
    state: "{{ pagespeed_exporter_service_state }}"
    enabled: "{{ pagespeed_exporter_service_enabled }}"
    daemon_reload: yes